# vim:ft=kitty

## name: Gradient Dark
## author: iguruspain (https://github.com/iguruspain)
## license: MIT
## upstream: https://github.com/atelierbram/Base2Tone-kitty/blob/main/themes/base2tone-field-dark.conf
## blurb: duotone theme | teal/turqoise - bright field green

#: The basic colors

foreground #d3dae3
background #171b27
selection_foreground #d3dae3
selection_background #006b6b


#: Cursor colors

cursor #00943e
cursor_text_color #171b27


#: URL underline color when hovering with mouse

url_color #88f2e0


#: kitty window border colors and terminal bell colors

active_border_color #42524f
inactive_border_color #171b27
bell_border_color #037764
visual_bell_color none


#: OS Window titlebar colors

wayland_titlebar_color #006b6b
macos_titlebar_color #006b6b


#: Tab bar colors

active_tab_foreground #85ffb8
active_tab_background #38407b
inactive_tab_foreground #5a6d6a
inactive_tab_background #313c6d
tab_bar_background #171b27
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)

mark1_foreground #171b27
mark1_background #089b83
mark2_foreground #171b27
mark2_background #78877e
mark3_foreground #171b27
mark3_background #0eaa4f


#: The basic 16 colors

#: black
color0 #171b27
color8 #5a6d6a

#: red
color1 #964b70
color9 #c0392b

#: green
color2 #85ffb8
color10 #006b6b

#: yellow
color3 #d8ff7e
color11 #fdbc4b

#: blue
color4 #25d0b4
color12 #667a77

#: magenta
color5 #9b59b6
color13 #8e44ad

#: cyan
color6 #40ddc3
color14 #25d46e

#: white
color7 #d3dae3
color15 #ffffff
